const projectAsthana = [
  {
    caption_address: "Asthana Kemang",
    db_profile: "DBLIVE",
    descs: "ASTHANA KEMANG",
    email: "mgr@ifca.co.id",
    entity_cd: "1201",
    entity_name: "PT SINTESIS KREASI BERSAMA",
    http_add: null,
    nup: "1",
    picture_path:
      "https://dev.ifca.co.id:4414/webasthana/public/storage/project-mobile/asthana_kemang.jpg",
    picture_url:
      "https://dev.ifca.co.id:4414/webasthana/public/storage/project-web/asthana_kemang.jpg",
    product_cd: null,
    project_descs: "ASTHANA KEMANG",
    project_no: "1201",
    project_status: "1",
    rowID: "5",
    row_number: "3",
    seq_no: "5",
    status: "1",
    userid: "MGR       ",
  },
];

const projectAsthanaDetail = {
  download: [],
  feature: [
    {
      audit_date: "2024-06-27 16:56:58.000",
      audit_user: "MGR",
      entity_cd: "1201",
      feature_info:
        "<p>Asthana merupakan apartemen eksklusif yang terletak di area Kemang, salah satu area paling prestisius di Jakarta Selatan. Dirancang dengan sentuhan arsitektur Jawa modern, Asthana Kemang tidak hanya menampilkan kesan elegan dan kemewahan, tetapi juga menghormati dan merayakan kekayaan budaya serta seni Indonesia. Sebagai hasil kolaborasi visioner dari para ahli terkemuka, Asthana Kemang menetapkan standar baru untuk ruang hidup modern di lingkungan perkotaan.</p><p>FACILITIES</p><ul><li>Jogging Track</li><li>Swimming Pool</li><li>Tennis Court</li><li>Commercial Area</li><li>Business Center</li><li>Function Room</li><li>Sky Lounge</li><li>24 Hours Security</li></ul>",
      project_no: "1201",
      rowID: "1",
    },
  ],
  gallery: [
    {
      audit_date: "2024-06-27 17:04:01.000",
      audit_user: "MGR",
      entity_cd: "1201",
      gallery_title: "Asthana - 1 Bedroom",
      gallery_url:
        "https://dev.ifca.co.id:4414/webasthana/public/storage/project-gallery/1201_1201_1_br.jpg",
      line_no: "1",
      project_no: "1201",
      rowID: "28",
    },
    {
      audit_date: "2024-06-27 17:04:30.000",
      audit_user: "MGR",
      entity_cd: "1201",
      gallery_title: "Asthana - 1 Bedroom",
      gallery_url:
        "https://dev.ifca.co.id:4414/webasthana/public/storage/project-gallery/1201_1201_1_br_-2.jpg",
      line_no: "2",
      project_no: "1201",
      rowID: "29",
    },
    {
      audit_date: "2024-06-27 17:04:53.000",
      audit_user: "MGR",
      entity_cd: "1201",
      gallery_title: "Asthana - 1 Bedroom",
      gallery_url:
        "https://dev.ifca.co.id:4414/webasthana/public/storage/project-gallery/1201_1201_1_br_-3.jpg",
      line_no: "3",
      project_no: "1201",
      rowID: "30",
    },
  ],
  overview: [
    {
      audit_date: "2024-07-12 17:17:08.000",
      audit_user: "MGR",
      entity_cd: "1201",
      overview_info:
        "<div>Asthana Kemang adalah apartemen eksklusif yang terletak di salah satu lokasi paling prestisius Jakarta Selatan. Apartemen kami dirancang dengan sentuhan arsitektur Jawa modern, yang tidak hanya menampilkan kesan elegan dan kemewahan, tetapi juga menghormati dan merayakan kekayaan budaya serta seni Indonesia.</div><div><br></div><div>Terletak di lingkungan Kemang yang dinamis, Asthana Kemang menawarkan akses mudah ke berbagai pusat perbelanjaan, rekreasi, dan perkantoran, menjadikannya pilihan ideal untuk kehidupan urban yang harmonis dan berkelas.</div>",
      project_no: "1201",
      rowID: "2",
      url_brochure: null,
      youtube_link: "8PYiQoyP2UU",
    },
  ],
  plan: [],
  project: [
    {
      RowID: "110",
      act_complete_dt: null,
      activity_cd: " ",
      address1: "JL. AMPERA RAYA NO.1A RT.002 RW.004",
      address2: "CILANDAK TIMUR PASAR MINGGU",
      address3: "JAKARTA SELATAN",
      approval_status: "B",
      area: null,
      audit_date: "2023-11-20 16:25:45.937",
      audit_user: "MGR",
      auth_vo: ".00",
      award_date: null,
      bank_cd: null,
      booking_fee: null,
      calendar: null,
      caption_address: null,
      claim_interval: "0",
      claim_method: " ",
      claim_todate: ".00",
      completion_date: null,
      const_sch: null,
      contact_email: null,
      contact_person: null,
      contact_telno: null,
      contract_amt: ".00",
      coordinat_address: "Asthana Kemang",
      coordinat_name: "Asthana Kemang",
      coordinat_project: "https://maps.app.goo.gl/jv98Fta4xdnDnjt57",
      currency_cd: "IDR",
      data_type: "I",
      debtor_acct: " ",
      debtor_no: "5",
      debtor_type: "03",
      default_bank_code: null,
      dept_cd: "0000",
      descs: "ASTHANA KEMANG",
      designation: null,
      direction_map: null,
      div_cd: "0000",
      doc_no: "0",
      duration: null,
      email_add: "info@asthanakemang.co.id",
      entity_cd: "1201",
      est_cost: ".00",
      facebook_url: null,
      financier_type: null,
      hidden_picture_url: null,
      instagram_url: null,
      kwitansi_trx: "KW",
      last_bill_date: null,
      location: "03",
      logo: "Ashta.bmp",
      max_ret_percent: ".00",
      memo_acct: " ",
      memo_cd: " ",
      min_claim_amt: ".00",
      nut_prefix: null,
      office_no: null,
      owner_type: "03",
      pay_bank_cd: null,
      payment_cd: null,
      penalty: ".00",
      picture_url: null,
      post_cd: null,
      post_sch_flag: null,
      prev_recog_profit: ".00",
      profit_acct: " ",
      project_date: null,
      project_factor: ".00",
      project_group: null,
      project_no: "1201",
      project_ref: "SKB",
      project_rev_cd: " ",
      project_status: "A",
      project_type: "APT",
      remarks: null,
      ret_acct: " ",
      ret_cd: " ",
      ret_limit: ".00",
      ret_percent: ".00",
      ret_release_date: null,
      ret_todate: ".00",
      revenue_acct: " ",
      selling_price: null,
      sk_no: null,
      solicitor_type: null,
      start_date: "2010-01-01 00:00:00.000",
      tower: null,
      virtual_entity: null,
      wa_no: "+62 8119660900",
      web_url: null,
      wip_acct: " ",
      wstatus: "A",
      youtube_url: null,
    },
  ],
  surrounding: [
    {
      amenities_info:
        '<p><span style="font-size: 0.875rem;">Stasiun MRT Cipete raya<br></span><span style="font-size: 0.875rem;">Terminal Bus Pasar Minggu</span></p>',
      amenities_title: null,
      amenities_type: "I",
      amenities_url: null,
      audit_date: "2024-06-27 17:18:31.000",
      audit_user: "MGR",
      entity_cd: "1201",
      project_no: "1201",
      rowID: "13",
    },
    {
      amenities_info:
        '<p><span style="font-size: 0.875rem;">SMA Kolese Gonzaga<br></span><span style="font-size: 0.875rem;">Sekolah Pelita Harapan<br></span><span style="font-size: 0.875rem;">High Scoop Indonesia</span></p>',
      amenities_title: null,
      amenities_type: "S",
      amenities_url: null,
      audit_date: "2024-06-27 17:18:31.000",
      audit_user: "MGR",
      entity_cd: "1201",
      project_no: "1201",
      rowID: "14",
    },
    {
      amenities_info:
        '<p><span style="font-size: 0.875rem;">RSIA Kemang<br></span><span style="font-size: 0.875rem;">RSUD Pasar Minggu<br></span><span style="font-size: 0.875rem;">RSIA Brawijaya Antasari<br></span><span style="font-size: 0.875rem;">RS Pondok Indah</span></p>',
      amenities_title: null,
      amenities_type: "H",
      amenities_url: null,
      audit_date: "2024-06-27 17:18:31.000",
      audit_user: "MGR",
      entity_cd: "1201",
      project_no: "1201",
      rowID: "15",
    },
    {
      amenities_info:
        '<p><span style="font-size: 0.875rem;">Lippo Mall Kemang<br></span><span style="font-size: 0.875rem;">Pejaten Village<br></span><span style="font-size: 0.875rem;">Gandaria City</span></p>',
      amenities_title: null,
      amenities_type: "O",
      amenities_url: null,
      audit_date: "2024-06-27 17:18:31.000",
      audit_user: "MGR",
      entity_cd: "1201",
      project_no: "1201",
      rowID: "16",
    },
  ],
};

export { projectAsthana, projectAsthanaDetail };
